# Generated by Django 5.0.6 on 2024-06-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='old_files',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
