# Generated by Django 5.0.6 on 2024-06-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_entry_old_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='tag_list',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
