# Generated by Django 5.0.6 on 2024-06-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_entry_tag_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='tag_list',
        ),
    ]
