# Generated by Django 5.0.6 on 2024-06-17 11:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_remove_entry_tag_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
    ]
