# Generated by Django 5.0.6 on 2024-06-17 12:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_alter_entry_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
    ]
