# Generated by Django 5.0.6 on 2024-06-01 15:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_alter_entry_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='raw'),
        ),
    ]
