# Generated by Django 5.0.6 on 2024-06-03 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_alter_entry_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
