# Generated by Django 5.0.6 on 2024-06-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_alter_entry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
