# Generated by Django 5.0.6 on 2024-06-08 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_alter_entry_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_entries', through='mainpage.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
