# Generated by Django 5.0.6 on 2024-06-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_entry_liked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='liked_users',
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
