# Generated by Django 5.0.6 on 2024-06-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_remove_entry_liked_users_comment_updated_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='likes',
        ),
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
